services:
  payment_api:
    container_name: payment_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_CONNECTION_STRING=Host=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
    ports:
      - "5083:80"
      - "7052:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    restart:
      always

  postgres_db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart:
      always
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    restart:
      always
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin:
